version: '3.5'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tegnoorg-recipeapp
    ports:
     - '3000:3000'
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules